### ISSUE TITLE
When is this app starting? 

### ISSUE THREAD

**Issue by gngchrs** [Laravel254/Community_App#2]
Been watching and not seeing any progress. Eager contributor here!! @mwaa

**Comment by mwaa** [comment]
@andela-cganga  Will be setting up the base code over the weekend. And at the same time make a test run of community sharing code/resources/snippets this coming week to determine if the app will have sufficient usage

**Comment by gngchrs** [comment]
@mwaa awesome.

**Comment by RowlandOti** [comment]
Eager contributor too.

**Comment by gngchrs** [comment]
yeah @RowlandOti , @mwaa we are availbale to help for any blockers

**Comment by rowino** [comment]
Hey all, had a look at what Mwaa had setup earlier?

**Comment by gngchrs** [comment]
@rowino Was there another setup? The repo was just built with a brief description

**Comment by mwaa** [comment]
@gangachris, @RowlandOti  and Everyone else you can checkout the repo at http://laravel254.github.io/share-book/

**Comment by RowlandOti** [comment]
@mwaa finally!!
